### ISSUE TITLE
Provide better support for custom binary serializers

### ISSUE THREAD

**Issue by e-nikolov** [WebReflection/coincident#31]
Continuing the discussion from https://github.com/WebReflection/coincident/issues/29#issuecomment-1771172071. I have a Polyscript use case for a binary protocol that is used for communicating between python workers on different machines (via WebRTC). 

Internally coincident converts a Uint16Array to string which is then passed to `JSON.parse()`. Currently coincident only supports custom string serializers. Ideally in my case the worker and main thread should be able to transmit binary data without having to go through the process of turning binary data -> JSON string -> JSON parse -> binary data.

Is this technically feasible?

**Comment by WebReflection** [comment]
> go through the process of turning binary data -> JSON string -> JSON parse -> binary data.

let me try to explain all steps ...

> turning binary data -> JSON string

that's actually how any returned value from the *main* world must be passed to the worker ... if it's not serializable as JSON, or structuredClone, it can't survive the main -> worker dance.

This assumes anything you return from main is a *JS* valid reference/data to pass as result ... so here my counter question: why is the result from main a buffer, likely out of expensive computation things, instead of being main just the "slow zombie" to ask results about operations?

This question exposes the idea behind coincident: slow expensive things on Workers, not on main .. if main returns very expensive things, your use-case is a bit upside-down here ... I hope this makes sense.

> string -> JSON parse

that's not actually what happens ... worker waits for a result from main, there's no field in this project to let main return anything as it is, but there's a need to parse back out of the main previous result, what is it that is returned.

That's the contract behind the scene ... you invoke something from main, how are you going to understand the answer?

Once again, there's no field/property to let anything through and pass it through as it is ... do you have a concrete example of what you are trying to do and where is the computation waste?

> JSON parse -> binary data.

I understand if binary data is all you are after, the stringify / parse dance is indeed not desired ... but here I wonder: would your own binary parser satisfy callbacks returning JS data among binary results satisfy all your requirements?

My gut feeling is that once I enable your own binary thing idea, you won't be able to ask for a boolean, a string, or just a returning object, from the main thread anymore ... is this OK to you?

**Comment by WebReflection** [comment]
in case it's not clear at the technical level, we're dealing with *Atomics* and *SharedArrayBuffer* ... any conversation must be somehow binary/serializable as *SharedArrayBuffer* and while I could pass just the buffer when it's returned, I need to change the dance when that's the case ... in short: let's say your function returned a TypedArray ... would it be OK to have that transfered as it is? This means that you can't return `{some: typedArrayData}` as that's JS and must be converted into binary data so everything will be the same *but* if you return `typedArrayData` I can actually just store the constructor type and its buffer, without needing to convert it via JSON.

This is a lot of work/changes for a use case that is still not super clear to me, as "*why do you pass big data from main?*" is still my question, while you can use `coincident.transfer(hugeBuffer)` to instead pass huge data form a worker to main without needing any serialization at all.

**Comment by e-nikolov** [comment]
> that's actually how any returned value from the main world must be passed to the worker ... if it's not serializable as JSON, or structuredClone, it can't survive the main -> worker dance.

This is clear, but JSON is human readable and not very efficient for binary data. I'd prefer using a more binary friendly format, e.g. [CBOR](https://datatracker.ietf.org/doc/html/rfc8949), ([cbor-x](https://www.npmjs.com/package/cbor-x)) or ([MessagePack](https://www.npmjs.com/package/msgpackr)). They are more or less drop in replacements for JSON, but they serialize to a non-ascii Uint8Array instead of string. They support structuredClone as well.

<details>
  <summary>(Expand/Collapse) An example of how they compare in terms of serializing objects that contain binary data </summary>

<table>
<tr>
<th></th>
<th width="200px">encoding</th>
<th width="200px">decoding</th>
<th width="200px">size</th>
<th width="100px">data</th>
<th colspan="2"></th>
</tr>
<tr>
<td>Input</td>
<td></td>
<td></td>
<td>~50 bytes</td>
<td colspan="2">

```js
{ a: 1000, b: true, c: { d: { e: { f: 1000 } } }, z: new Uint8Array([34, 0, 0, 0, 241, 98, 92, 191, 255, 255, 255, 255, 4, 0, 109, 234, 6, 20, 109, 247, 209, 11, 107, 30, 34, 15, 110, 220, 163, 50, 204, 3, 129, 30, 173, 43, 0, 2, 86, 104, 65, 63, 27, 191, 23, 23]) }
```

</td>
</tr>
<tr>
<td>JSON</td>
<td>~161,823 ops/sec</td>
<td>~548,823 ops/sec</td>
<td>421 bytes</td>
<td colspan="2">

```js
// {"a":1000,"b":true,"c":{"d":{"e":{"f":1000}}},"z":{"0":34,"1":0,"2":0,"3":0,"4":241,"5":98,"6":92,"7":191,"8":255,"9":255,"10":255,"11":255,"12":4,"13":0,"14":109,"15":234,"16":6,"17":20,"18":109,"19":247,"20":209,"21":11,"22":107,"23":30,"24":34,"25":15,"26":110,"27":220,"28":163,"29":50,"30":204,"31":3,"32":129,"33":30,"34":173,"35":43,"36":0,"37":2,"38":86,"39":104,"40":65,"41":63,"42":27,"43":191,"44":23,"45":23}}
Uint8Array[123,34,97,34,58,49,48,48,48,44,34,98,34,58,116,114,117,101,44,34,99,34,58,123,34,100,34,58,123,34,101,34,58,123,34,102,34,58,49,48,48,48,125,125,125,44,34,122,34,58,123,34,48,34,58,51,52,44,34,49,34,58,48,44,34,50,34,58,48,44,34,51,34,58,48,44,34,52,34,58,50,52,49,44,34,53,34,58,57,56,44,34,54,34,58,57,50,44,34,55,34,58,49,57,49,44,34,56,34,58,50,53,53,44,34,57,34,58,50,53,53,44,34,49,48,34,58,50,53,53,44,34,49,49,34,58,50,53,53,44,34,49,50,34,58,52,44,34,49,51,34,58,48,44,34,49,52,34,58,49,48,57,44,34,49,53,34,58,50,51,52,44,34,49,54,34,58,54,44,34,49,55,34,58,50,48,44,34,49,56,34,58,49,48,57,44,34,49,57,34,58,50,52,55,44,34,50,48,34,58,50,48,57,44,34,50,49,34,58,49,49,44,34,50,50,34,58,49,48,55,44,34,50,51,34,58,51,48,44,34,50,52,34,58,51,52,44,34,50,53,34,58,49,53,44,34,50,54,34,58,49,49,48,44,34,50,55,34,58,50,50,48,44,34,50,56,34,58,49,54,51,44,34,50,57,34,58,53,48,44,34,51,48,34,58,50,48,52,44,34,51,49,34,58,51,44,34,51,50,34,58,49,50,57,44,34,51,51,34,58,51,48,44,34,51,52,34,58,49,55,51,44,34,51,53,34,58,52,51,44,34,51,54,34,58,48,44,34,51,55,34,58,50,44,34,51,56,34,58,56,54,44,34,51,57,34,58,49,48,52,44,34,52,48,34,58,54,53,44,34,52,49,34,58,54,51,44,34,52,50,34,58,50,55,44,34,52,51,34,58,49,57,49,44,34,52,52,34,58,50,51,44,34,52,53,34,58,50,51,125,125]
```

</td>
</tr>
<tr>
<td>CBOR</td>
<td>~480,110 ops/sec</td>
<td>~1,261,678 ops/sec</td>
<td>101 bytes</td>
<td colspan="2">

```js
Uint8Array[217,223,255,134,25,224,0,132,97,97,97,98,97,99,97,122,25,3,232,245,217,223,255,131,25,224,1,129,97,100,217,223,255,131,25,224,2,129,97,101,217,223,255,131,25,224,3,129,97,102,25,3,232,88,46,34,0,0,0,241,98,92,191,255,255,255,255,4,0,109,234,6,20,109,247,209,11,107,30,34,15,110,220,163,50,204,3,129,30,173,43,0,2,86,104,65,63,27,191,23,23]
```

</td>
</tr>
<tr>
<td>MessagePack</td>
<td>~490,198 ops/sec</td>
<td>~1,231,346 ops/sec</td>
<td>85 bytes</td>
<td colspan="2">

```js
Uint8Array[212,114,64,148,161,97,161,98,161,99,161,122,205,3,232,195,212,114,65,145,161,100,212,114,66,145,161,101,212,114,67,145,161,102,205,3,232,196,46,34,0,0,0,241,98,92,191,255,255,255,255,4,0,109,234,6,20,109,247,209,11,107,30,34,15,110,220,163,50,204,3,129,30,173,43,0,2,86,104,65,63,27,191,23,23]
```

</td>
</tr>
</table>

For larger inputs the differences become more significant.

</details>

> This assumes anything you return from main is a JS valid reference/data to pass as result ... so here my counter question: why is the result from main a buffer, likely out of expensive computation things, instead of being main just the "slow zombie" to ask results about operations?
> This question exposes the idea behind coincident: slow expensive things on Workers, not on main .. if main returns very expensive things, your use-case is a bit upside-down here ... I hope this makes sense.

In my case the expensive computations are done by the workers, but it's a Peer-to-Peer application with each Peer running a Polyscript worker in their own browser and communicating over WebRTC/PeerJS. As far as I'm aware the workers can't use WebRTC directly and have to go through the main threads.

The function calls between the threads don't return anything and don't need to be awaited to complete - they are event triggers. It's either a worker asking the main thread to send some binary data to another Peer or the main thread passing some binary data that arrived from another Peer to the worker. The amount of data sent from one Peer to another is around 39 MB over 750 000 messages over a period of ~10 minutes.

I have a limited understanding of coincident since I'm only using it via Polyscript. I may be misusing it for asyncronous calls when it's only meant for syncronous calls? You also mentioned the `concident.transfer()` function, would that be a better fit or is it also meant for syncronous calls?

The lifecycle of a message between the workers of 2 peers, "Peer A" and "Peer B" looks like this:

<details open>
  <summary>(Expand/Collapse) </summary>

```mermaid
flowchart LR
  subgraph Peer A
   A("(1) worker")
   B("(3) main")
  end
  A--"(2) coincident"-->B
   subgraph Peer B
   B--"(4) WebRTC/\nPeerJS"-->C("(5) main")
   C--"(6) coincident"--> D("(7) worker")
end
```

1. Python Worker on Peer A

   - creates a message that contains a secret share computed via the [MPyC](https://github.com/lschoe/mpyc) framework, which serializes it to binary via struct.pack(). The resulting message is non-ascii, but when escaped can look like this:

   ```python
   b'\x06\x00\x00\x00\xc9\x93\\\xc0\xff\xff\xff\xff\x04\x00\x80\x99\x1b\x01'
   ```

   - worker calls a main thread function (sendRuntimeMessage) via a coincident proxy and passes the serialized value, as well as the destination Peer's ID (Peer B). The worker does not need to await the result of this call, but it does because of xworker.sync.

2. Coincident handles the message (as far as I understand) by:

   - (Worker) JSON.stringify() -> Atomics.wait()
   - (Main) JSON.parse() -> Run the Main Thread function -> Atomics.notify()

3. Main thread on Peer A fires an event to notify PeerJS that it needs to transport the message and immediately returns in order to not block the Worker

4. PeerJS serializes the message with some added fields via MessagePack and transmits it to Peer B

5. Main thread on Peer B receives the message and forwards it to the appropriate worker callback via coincident

6. Coincident does the JSON.stringify() -> Atomics.wait() stuff (?) from main to worker on Peer B

7. Worker on Peer B handles the message by passing it to an asyncio coroutine that is waiting for it or stores it for later use

**Comment by WebReflection** [comment]
I am not sure I am following but this:

```
b'\x06\x00\x00\x00\xc9\x93\\\xc0\xff\xff\xff\xff\x04\x00\x80\x99\x1b\x01'
```

is a perfectly valid string that can be passed as such between threads ... now you probably think "but I don't want btoa and aob" conversion, to which I agree, but then again with *coincident* you can transfer buffers as they are ... true that this is not directly implemented in Polyscript, and there is also a caveat: you source of the buffer won't have data for that buffer anymore, as it's smoke-tested already in here: https://github.com/WebReflection/coincident/blob/main/test/transfer.html

About "no need to await" ... the worker using `sync` will always be a synchronous blocking operation, it's in the name after all ... it doesn't matter if the main callback is asyn or not, because that is always already too late for an inevitably async operation made sync by Atomics ... postMessage back and forward is *async* no matter what so ... that's not the issue.

The issue here seems to be the lack of ability to not serialize data when certain conditions are met ... and here, in coincident, you can pass your own `parse` and `stringify` function which can already disambiguate on *stringify* and do the right thing on *parse* but the Atomics dance still need to know how much data traveled so that it can extract that data from the *SharedArrayBuffer* ... in short, whatever you are trying to do, has ho be compatible with *SharedArrayBuffer* so if I can store there strings, you can store there anything UTF-16 compatible, as long as you are able to revive it back once delivered, that's the custom `parse` and `stringify`.

None of this is part of *polyscript* because to target most common use cases we automatically use `structuredClone` compatible algorithm, but please note that such procedure already takes care of binary data so that your comparisong on JSON is not really what happens in polyscript because in polyscript the cloning already works with binary data.

  * this is how we initialize coincident via structured-clone: https://github.com/pyscript/polyscript/blob/main/esm/worker/class.js#L1-L2
  * this is serialization in structured clone for typed arrays: https://github.com/ungap/structured-clone/blob/main/esm/serialize.js#L81-L82 ... the data is just spread as numbers as it is, nothing else changes

The dance is that typed arrays are just spread, then stringified as an array of numbers, then revived exactly like that constructor form that array of numbers, which is the equivalent of a clone dance ... JSON can't even deal with typed arrays so it's really not a comparison target for any discussion.

**Comment by WebReflection** [comment]
by the way, the `xworker` *is* a `Worker` itself, so if you don't need to sync anything, you can still use `addEventListener` there and receive the data via `postmessage` which uses internally the structured clone algorithm already, so you should be able to orchestrate any dance across multiple workers as you like ... the `sync` is an extra feature as extend, not the only way to use the `xworker` ... maybe this helps? add a `message` handler that receives data as *typed binary data* and call it a day, nothing need to change in either *coincident* or *polyscript* in that case.

**Comment by WebReflection** [comment]
worth adding ... if you `xworker.postMessage(typedArray)` that doesn't conflict with *coincident* or *polyscript* because there is a private/unique message channel that avoid conflicting with regular worker/main exchanges ... so you can `postMessage` via xworker, you can have a listneer on main that forward that data via the xworker and a listener for `message`, and any other worker can listen to data ... this should work out of the box and it won't require any 3rd party library.

**Comment by e-nikolov** [comment]
> worth adding ... if you xworker.postMessage(typedArray) that doesn't conflict with coincident or polyscript because there is a private/unique message channel that avoid conflicting with regular worker/main exchanges ... so you can postMessage via xworker, you can have a listneer on main that forward that data via the xworker and a listener for message, and any other worker can listen to data ... this should work out of the box and it won't require any 3rd party library.

I think initially I started doing it this way, but then switched to `sync` utilities because it was convenient to be able to call functions. Now that you mention it, it's kind of obvious that it's only meant for sync things.

**Comment by WebReflection** [comment]
@e-nikolov I went eventually ahead and tried an alternative approach ... please read all caveats in the MR description, but also read results in terms of performance boost: https://github.com/WebReflection/coincident/pull/33

I am closing this as *won't fix* for the time being, as branched logic and new possible unknowns don't seem worth it that 2X speed gain, when the use case is edge/rare enough, and we're still talking 2 VS 4 milliseconds.
