### ISSUE TITLE
Using an iframe as coincident's context

### ISSUE THREAD

**Issue by jed** [WebReflection/coincident#38]
I'm attempting to use an iframe with coincident, like this:

### index.html
```html
<!DOCTYPE html>
<body>
<script type="module">
  import coincident from 'https://unpkg.com/coincident/window';

  let iframe = document.createElement('iframe');
  iframe.src = './iframe.html';
  document.body.appendChild(iframe);

  coincident(iframe.contentWindow);
</script>
```

### iframe.html
```html
<!DOCTYPE html>
<body>
<script type="module">
  import coincident from 'https://unpkg.com/coincident/window';

  const {proxy, window, isWindowProxy} = coincident(self);

  const {document} = window;
</script>
```

but get the error `Uncaught TypeError: Illegal invocation` when trying to access `document` in `iframe.html`... any chance there's another way to use coincident with iframes?

**Comment by WebReflection** [comment]
Hi Jed, the issue is that on the main thread you don't get to use *Atomics* or *SharedArrayBuffer* in a way that `Atomics.wait` makes sense, as it's forbidden to block the main thread with *Atomics* and I think that applies to *iframes* too.

this is out of my gut though, I need to investigate what's going on behind the scene but I think you're playing *main* VS *another main* by using iframes instead of workers and here my question: why do you need an *iframe* there, where you have `parent` access from there to do, when authorized, anything you like and vice-versa?

**Comment by jed** [comment]
i'm working on a use case that needs off-main-thread DOM operations, so was looking to use a cross-origin iframe for that, which isn't reflected in this repro. is there another approach that you think would work?

**Comment by WebReflection** [comment]
you can reflect the current DOM in a worker via LinkeDOM or uhtml/dom modules ... you pass the `document.body.outerHTML` to that worker, you parse it as document, you then have ability to perform most common DOM operations.

This is the first/quick answer that comes to mind, but while that dance won't be blocking, it would be probably a tad slow on bootstrap ... iframes are not famous for speed neither, so maybe a worker with any of those modules in would be a solution? For LinkeDOM there is an explicit `linkedom/worker` export, if that helps.

**Comment by jed** [comment]
interesting, that's a good point. why do you think the bootstrap would be slow for this use case?
