### ISSUE TITLE
Add Leader Election Support via Web Locks API 

### ISSUE THREAD

**Issue by nickchomey** [WebReflection/coincident#40]
Thanks for building and sharing this! It looks like a great improvement over comlink, and of course over the native api - to say nothing of how it integrates with the rest of your tooling, like uhtml.

I use sharedworkers to maintain a single websocket connection to the backend for all tabs in a browser. 
Comlink [describes how to use SharedWorkers](https://github.com/GoogleChromeLabs/comlink?tab=readme-ov-file#sharedworker) by passing in `SharedWorker.port` rather than just the Worker, such that when `worker.postMessage()` is called, it exists.

```js
async function init() {
  const worker = new SharedWorker("worker.js");
  /**
   * SharedWorkers communicate via the `postMessage` function in their `port` property.
   * Therefore you must use the SharedWorker's `port` property when calling `Comlink.wrap`.
   */
  const obj = Comlink.wrap(worker.port);
```

Even your own [proxied-worker](https://github.com/WebReflection/proxied-worker?tab=readme-ov-file#as-sharedworker) has support for shared workers!

So, would something like this be possible with Coincident? [This line in index.js](https://github.com/WebReflection/coincident/blob/main/esm/index.js#L49) makes it seem like it might work. 

`const sendMessage = postPatched || self.postMessage;`

If so, could you confirm how to do this? Something like this?

```js
const worker = new SharedWorker('./shared-worker.js', {type: 'module'});
coincident(worker.port).enabler = async (...args) => {
  // do something sync or async with received args
  return {some: 'value'};
};
```

Also, would it be possible to use this to communicate between a sharedworker and dedicated worker? I could foresee me wanting to offload processing to dedicated workers when particular websocket messages come into the sharedworker - without needing to talk to the main thread. Either the sharedworker spawns its own dedicated workers (if possible?) or main thread spawns their own worker, with connects to the sharedworker. 

Thanks!

**Comment by WebReflection** [comment]
Hello there, and sorry for the late reply.

This project is used in production and it has a slightly different roadmap / priority queue and the current state is that I've rewritten it entirely, see https://github.com/WebReflection/coincident/pull/42

If I understand correctly your need for *SharedWorker* is related to the server side and the *WebSocket* previous port ... but you want to reuse that very same socket for multiple tabs.

I don't have any strong opinion around it, but it makes the *GC* related orchestration harder in terms of logic, as things can be held on multiple tabs, so works need to be done ... the good news though, is that I haven't refactored at all the `server` side story of this module in **v2** so there's plenty of room to consider that approach too.

This is because when it comes to workers, it's always the same main thread creating these, one or more, and current refactoring should grant that multiple workers can still use anything on main and vice-versa.

When it comes to *SharedWorker*, interfaced with workers, things are more convoluted by design.

All I am saying is that I will keep this requirement in mind whenever I'll rewrite the `coincident/server/main` and `coinsident/server/worker` exports, but I am afraid it won't be any time soon ... but it will happen, eventually.

**Comment by WebReflection** [comment]
> The more I think about it, the more I realize that its probably best to just implement myself - only create the coincident worker if the lock has been acquired, rather than have coincident abstract away the Locks API.

yeah, I am not sure what I should do here ... this enables a primitive to provide cross realms functions and/or access to the global main context (*window*) ... I don't know why anything else can't just use these primitives to literally do whatever they like 🤔

**Comment by WebReflection** [comment]
> I do think the initial issue asking how to use coincident with shared workers was quite valid and still worth documenting/addressing

sure, meanwhile this issue title changed to something I don't even know/understand or need to provide in here ... can we please stick with one issue/requirement per time so I can track/work on each of them separately?

**Comment by WebReflection** [comment]
P.S. I don't really care about Comlink here neither ... I tried that and gave *us* nothing easy to reason about and never worked after weeks of work trying to implement it ... anything they do is very different from what I do here so please provide use cases, no 3rd party libraries that are not comparable in terms of logic and/or implementation, thanks.

Also worth saying: if they solved a specific issue that is not solved in here, feel free to use their solution too in the meanwhile.

**Comment by WebReflection** [comment]
another P.S. it'd be great to have a SharedWorker issue without any extra thoughts/pollution in it ... just what issue it's trying to solve, how you would see it working (as expectations) and I'll try to wrap my head around that 😉
