### ISSUE TITLE
Compatibility Issue with coincident v2 in Next.js 14 Environment

### ISSUE THREAD

**Issue by ocodekr** [WebReflection/coincident#44]
Thank you for releasing such an awesome library.

I'm currently testing in a turborepo and next.js 14 environment. While coincident v1 worked without issues, coincident v2 does not. 

Upon investigation, I found that coincident v2 has been changed to extend Worker, which seems incompatible with next.js.

```javascript
  class Worker extends exports.Worker {
    constructor(url, options) {
	  // ...
    }
  }
```
https://github.com/WebReflection/coincident/blob/5f91c2b2d2b9ad00c48442f53031d1602b99f289/src/window/main.js#L55

More details can be found in this link.
https://github.com/vercel/next.js/issues/31009#issuecomment-1782410371

I hope this issue can be addressed soon.

Thank you.

**Comment by WebReflection** [comment]
> I hope this issue can be addressed soon.

you mean at *Next.js 14* level, right? I am using standard ECMAScript here and that extend is meant to stay.

You can also stick with v1 until they fix their issues, but the code here is simply *JS* and it's guaranteed to work in *JS*.

If it doesn't, it's not *JS* fault and I am not looking forward to see everyone holding back standard *JS* because *Next.js* has issues, to be honest ... apologies if this wasn't the answer you were looking for, for our purpose this code works wonderfully well.

**Comment by WebReflection** [comment]
Also relevant? https://github.com/vercel/next.js/issues/31009#issuecomment-2090165287

if you don't `next dev --turbo` but just `next dev` everything should be fine.

**Comment by WebReflection** [comment]
P.S. v1 is still rock solid so you can really avoid moving to v2 if you never had issues with v1.

**Comment by WebReflection** [comment]
to expand entirely ... it's explained in the [Breaking Changes](https://github.com/WebReflection/coincident/releases/tag/v2.0.0) why the current state is this one, re-writing related points:

* it was ugly and less powerful to pass along already initialized *Worker* instances ... the `Worker` class now does bootstrap correctly itself while still extending the native `Worker` class provided by the environment
* the `Worker` class also ensures that worker wasn't already bootstrapped and somehow "*ruined*" or polluted elsewhere before being passed to `coincident(worker)` utility
